apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: ksm-collector
  namespace: app
spec:
  mode: deployment # This configuration is omittable.
  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'kube-state-metrics'
              scrape_interval: 15s
              static_configs:
                - targets: ['app-kube-state-metrics.app.svc.cluster.local:8080']

    
    processors:
      batch:
        timeout: 5s
        send_batch_size: 100

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"


    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [prometheus]